### PR TITLE
Add coloring to the messages

### PR DESCRIPTION
**Pull request by andrusha**
That's what it looks like:

screenshot 2015-03-11 21 58 14

### CODE REVIEW

**Comment by phallstrom** [comment]
@andrusha - Neat! Can you tweak the specs so they pass?

**Comment by andrusha** [comment]
@phallstrom sure thing, I'm on it.

As for periods, it's just that none of the integrations I saw uses them.

**Comment by andrusha** [comment]
@phallstrom I'm not really happy with the way specs looks now, so suggestions are welcomed, but it works.

**Comment by phallstrom** [comment]
@andrusha Pushed 0.1.5 to rubygems. Thanks!

**Pull request merged**
